language: python
python:
    - "3.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip3 install -U platformio
    - platformio update

script:
    - cd examples ; platformio run -c .travis.platformio.ini
